### PR TITLE
Drop CentOS and Redhat 7 support

### PR DESCRIPTION
**Pull request by zilchms**
includes: #454 #455

### CODE REVIEW

**Comment by TheMeier** [comment]
Drop Debian 10 too?

**Comment by ekohl** [comment]
What's the reason to drop CentOS 7? It's not EOL yet. At least, not until June.

**Comment by zilchms** [comment]
Thats actually a good point, I misread the endoflife.org chart...
Time to fix the centos7 failures then

**Comment by zilchms** [comment]
The unit tests are failing due to differences between puppet-facterdb facts for redhat. When those are fixed and released, the unit tests here should be working.
As for the CentOS 7 failures: no idea yet

**Comment by zilchms** [comment]
Dropping CentOS and Redhat 7 as per: https://voxpupuli.org/blog/2024/05/08/CentOS-7-CentOS-Stream-8-deprecation/

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
