### PR TITLE
Adding Ubuntu 20.04 (Focal) support

### PR DESCRIPTION
**Pull request by craigwatson**
#### Pull Request (PR) description
Adding support for Ubuntu 20.04 (Focal)

### CODE REVIEW

**Comment by bastelfreak** [comment]
thanks for the PR @craigwatson. can you also add Ubuntu 20 to the .sync.yml and .travis.yml to enable acceptance tests for it?

**Comment by Wesseldr** [comment]
Could someone please merge this request and get Ubuntu 20.04 LTS verified please 👍

**Comment by kenyon** [comment]
> Could someone please merge this request and get Ubuntu 20.04 LTS verified please +1

@Wesseldr the tests need to pass, and the merge conflicts need to be resolved.

**Comment by Wesseldr** [comment]
@craigwatson :pray: Thank you very much appreciate it.. :thumbsup:

**Comment by craigwatson** [comment]
@Wesseldr no worries! Unfortunately I don't have the time to dig into the CI failures, but from a quick check I can't see a reason for the problems 😞

**Comment by craigwatson** [comment]
I've had another look at this, and it seems that Puppet aren't publishing a Puppet 5 repo for 20.04, so that would account for that failure.

I can't figure out why the CI tests are failing for Puppet 6 though, the exact same change works perfectly on my real-life Ubuntu 20.04 machine.

@bastelfreak would you have any ideas here?

**Comment by bastelfreak** [comment]
We can ignore the ubuntu 20/04/puppet 5 failures. But I've no clue why Puppet 6 fails as well :(

**Pull request closed without merging**
