### PR TITLE
Update server.erb - fix proto for tcp client mode

### PR DESCRIPTION
**Pull request by ajjonesycomau**
Update server.erb - fix proto for tcp client mode so that it sets:
proto tcp
rather than
proto tcp-server

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @ajjonesycomau, thanks for this PR! Can you add a unit test to ensure the correct settings are written to the file? Also please rebase against our latest master branch.

**Comment by jimirocks** [comment]
This thing is blocking my usage of the module, can you guys proceed?

**Comment by bastelfreak** [comment]
Hi @jimirocks. As tagged on 2018-03-17, this PR needs at least a rebase. If you're interested in getting this merged, you can checkout the PR, rebase it and afterwards resubmit it as a new PR.

**Comment by bastelfreak** [comment]
Hi. I'm going to close this PR due to inactivity. Please reopen and rebase if you're still interested in it.

**Pull request closed without merging**
