### PR TITLE
Add Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jkroepke**

### CODE REVIEW

**Comment by jkroepke** [comment]
It depends on https://github.com/voxpupuli/beaker-hostgenerator/pull/248 and a public puppet release for jammy (https://tickets.puppetlabs.com/browse/PA-4233)

**Comment by jkroepke** [comment]
Looks like no jammy package available http://apt.puppetlabs.com/ but the repos are available - http://apt.puppetlabs.com/dists/jammy/index.html

**Comment by root-expert** [comment]
Meh, I thought they were out but it was just nightlies. We will wait until the actual release happens :D

**Comment by jkroepke** [comment]
puppet 7.18.0 planned release is 2022-07-12

**Comment by jkroepke** [comment]
https://apt.puppet.com/dists/jammy/index.html packages for 22.04 are present, but no deb which configure the repository.

**Comment by root-expert** [comment]
Yea, that's kinda weird tbh...

**Comment by jkroepke** [comment]
https://apt.puppet.com/puppet7-release-jammy.deb is there, but there is no deb file or puppet6

**Comment by root-expert** [comment]
Sorry for the spam, it should finally work (hopefully).

**Review by root-expert — APPROVED** [review]

**Review by smortex — APPROVED** [review]
LGTM

**Pull request merged**
