### PR TITLE
Add buster support

### PR DESCRIPTION
**Pull request by NITEMAN**
#### Pull Request (PR) description
Add Debian 10 (buster) support

#### This Pull Request (PR) fixes the following issues
Fixes #372 (superseeds)

### CODE REVIEW

**Comment by NITEMAN** [comment]
I think travis error comes from facter version not from the code itself.

**Comment by bastelfreak** [comment]
Hi, this should be fixed with https://github.com/voxpupuli/puppet-openvpn/pull/380. Can you please rebase after that's merged?

**Comment by NITEMAN** [comment]
Sure @bastelfreak

**Comment by NITEMAN** [comment]
@bastelfreak rebased, but now tests fail in a different unrelated way :(

Currently seeing if it's a easy one to fix

**Comment by NITEMAN** [comment]
That was an easy one to catch: https://github.com/voxpupuli/puppet-openvpn/pull/380/files#r436591258

Tests finally passing :sunglasses:

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
