### PR TITLE
Extending mail capabilities

### PR DESCRIPTION
**Pull request by antgel**
#### Pull Request (PR) description
Emails openvpn configuration to specified user(s).

### CODE REVIEW

**Comment by bastelfreak** [comment]
HI @antgel, thanks for this PR. I'm not sure if this is a good approach. Do we really need a python script to send out emails? Mail handling is a very very complicated topic because almost each environment is different.  It's maybe the best idea to realize mail handling with a dedicated module. I'm open for opinions from our @voxpupuli/collaborators here.

**Comment by xaque208** [comment]
I'd think this sort of code belongs in the manifests for a given infrastructure instead of the module here.  In my opinion, this makes too many assumptions to be useful generally, and strays away from the core of the module's primary purpose.  The exec here could still subscribe the resources in the module, but not need to be included with this project.

**Comment by wyardley** [comment]
Agree with @bastelfreak and @xaque208 here

**Comment by antgel** [comment]
Hi all, thanks for the feedback. @shapi78 wrote this, because it fits an internal need. We wanted to send it upstream to give back - perhaps we should have consulted before hacking away. I can't see us having time to devote to a significant refactor, so should I close this?

**Comment by Dan33l** [comment]
With PR as this :
  * to install python on node becomes mandatory . Python is not installed on supported OSes by default.
  * to receive mail is mandatory. I expect a switch true/false to define behaviour.
  * to use `localhost` as smtp relay is mandatory. I expect a parameter.

In my point of view,  3 locking points that should be resolved.

**Comment by oranenj** [comment]
@antgel I am not opposed to merging this functionality with the python script if it's documented in the README that python is required and that you make the other smaller changes I noted. It can be changed to be more portable later if that's required, most likely without affecting existing users.

**Comment by bastelfreak** [comment]
I still think that this, in the current implementation, is way to site-specific and should be handled in a profile.

**Pull request closed without merging**
